### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by halfmonty** [narmeenm94/Petra-Instagram#1]
I can't seem to find any contact method for you so I hope this reaches you.

In the gitter AR.js/Lobby you were asking question about samsung and the camera issue (I assume it's the multi-camera issue). You later wrote "Update: Solved it for Samsung note 10+ for browser and chrome."

Is it possible for you to share how you solved it? I'm in the same boat as are many other people in the gitter chat. Thank you very much.

**Comment by narmeenm94** [comment]
Hey there!
Yeah sure thing, here you'll find the solution and conversation that went on 😁

https://github.com/AR-js-org/AR.js/issues/121#issuecomment-775948765

**Comment by narmeenm94** [comment]
You need to change the dimensions as such:

"""go to your original script "The AR.js using Aframe" (this one: https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js) look for the following info and change the numbers from 640 and 480 to the numbers below:
// resolution of at which we initialize in the source image
sourceWidth: 1024,
sourceHeight: 776,
// resolution displayed for the source
displayWidth: 1024,
displayHeight: 776,
"""

There is a whole conversation in the link I sent previously, so I hope this helps 😁

**Comment by halfmonty** [comment]
Awesome! Thank you!
